apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sre
description: Simple application delivery pipeline
serialPipeline:
 stages:
 - targetId: develop
   profiles:
   - develop
 - targetId: staging
   profiles:
   - staging
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: develop
description: develop cluster
gke:
  cluster: projects/csmd-jcuendes-523/locations/europe-west1/clusters/my-gke-cluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
requireApproval: true
gke:
  cluster: projects/csmd-jcuendes-523/locations/europe-west1/clusters/my-gke-cluster
